### ISSUE TITLE
Hardware transcoding not working due to incorrect permissions

### ISSUE THREAD

**Issue by ovicus** [hotio/plex#14]
## Expected Behavior
On a device with Intel QuickSync, when `/dev/dri` is correctly mapped, Plex should use `/dev/dri/renderD128` for hardware transcoding.

## Current Behavior
Hardware transcoding not working due to permissions issue. 

### docker-compose.yml
```
version: "2.1"
services:
  plex:
    container_name: plex
    image: cr.hotio.dev/hotio/plex
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
      - PLEX_CLAIM=claim-REDACTED
      - PLEX_PASS=yes
    volumes:
      - /appdata/plex/config:/config
      - /appdata/plex/transcode:/transcode
      - /data/media:/media
    ports:
      - 32400:32400
    restart: unless-stopped
```

```
$ docker exec -it plex bash
$ ls -la /dev/dri
total 0
drwxr-xr-x 2 root   root        80 Nov  5 19:26 .
drwxr-xr-x 6 root   root       360 Nov  5 19:26 ..
crw-rw---- 1 nobody video 226,   0 Nov  5 19:24 card0
crw-rw---- 1 nobody   108 226, 128 Oct 31 16:13 renderD128

$ id hotio
uid=1000(hotio) gid=1000(hotio) groups=1000(hotio),100(users)
```
- Device `/dev/dri/renderD128` should be owned by group `render` that doesn't exist.
- User `hotio` should be member of `render` group.

As a result, Plex fails to use `/dev/dri/renderD128` to do hardware trancoding, with following message in the logs

```
DEBUG - [Req#14f/Transcode] Codecs: hardware transcoding: opening hw device failed - probably not supported by this system, error: Generic error in an external library
DEBUG - [Req#14f/Transcode] Could not create hardware context for hevc
```

## Steps to Reproduce
See above

## Workaround

```
$ docker exec -it plex bash
$ groupadd -g 108 render
$ usermod -aG render hotio
$ exit
$ docker restart plex
```

> These changes don't survive a system restart. When container is destroyed, these changes are lost.

## Environment
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.64-1-pve x86_64)
